name: Déploiement de l'API

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configurer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Installer les dépendances
        run: pip install -r requirements.txt
      - name: Exécuter les tests
        run: pytest test/

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configurer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Installer les dépendances
        run: |
          pip install -r requirements.txt
      - name: Déployer l'API
        run: |
          # Commandes pour déployer votre API (ex: sur Heroku, Render, etc.)
          echo "Déploiement en cours..."
